---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-spot-rescheduler
  namespace: kube-system
  labels:
    app: k8s-spot-rescheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-spot-rescheduler
  template:
    metadata:
      labels:
        app: k8s-spot-rescheduler
    spec:
      # Uncomment the following line if using RBAC
      serviceAccountName: k8s-spot-rescheduler
      containers:
        - image: <IMAGE_URI>
          name: k8s-spot-rescheduler
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          command:
            - k8s-spot-rescheduler
            - -v=2
            - --running-in-cluster=true
            - --namespace=kube-system
            - --housekeeping-interval=10s
            - --node-drain-delay=10m
            - --pod-eviction-timeout=2m
            - --max-graceful-termination=2m
            - --listen-address=0.0.0.0:9235
            - --on-demand-node-label=<ON_DEMAND_NODE_LABEL>
            - --spot-node-label=<SPOT_NODE_LABEL>
            # Set the following to false if you want to move sts as well
            - --exclude-sts=true
            # Uncomment the following if you need to move specific workload only.
            # Fill the value with your workload name string/substring
            - --workload-to-move=<WORKLOAD_NAME_SUBSTRING>
          ports:
          - name: http
            containerPort: 9235
